### PR TITLE
fix #291 -- support heterogenous quant config

### LINKED ISSUE #291: Qwen3 with heterogenous quant doesn't work
The following model `mlx-community/Qwen3-1.7B-4bit-AWQ` doesn't run in the mlx-swift-examples repo doesn't run. It fails with a mismatched shape error in the scales. I suspect it's due to the heterogenous quant not being parsed properly. See e.g. https://huggingface.co/mlx-community/Qwen3-1.7B-4bit-AWQ/blob/main/config.json#L20

### PR DESCRIPTION
**Pull request by davidkoski**
- support per layer quant config

### CODE REVIEW

File: Libraries/Embedders/BaseConfiguration.swift [hunk 1]
```diff
@@ -0,0 +1,155 @@
+// Copyright © 2025 Apple Inc.
+
+import Foundation
+
+/// Base ``LanguageModel`` configuration -- provides `modelType`
+/// and `quantization` (used in loading the model).
+///
+/// This is used by ``ModelFactory/load(hub:configuration:progressHandler:)``
+/// to determine the type of model to load.
+public struct BaseConfiguration: Codable, Sendable {
```
Comment (davidkoski) [inline Libraries/Embedders/BaseConfiguration.swift:10]: The embedders code has the same quant config.  Described below.

I wonder if we need an MLXCommon (above MLXLMCommon)?

File: Libraries/MLXLMCommon/BaseConfiguration.swift [hunk 2]
```diff
@@ -0,0 +1,155 @@
+// Copyright © 2025 Apple Inc.
+
+import Foundation
+
+/// Base ``LanguageModel`` configuration -- provides `modelType`
+/// and `quantization` (used in loading the model).
+///
+/// This is used by ``ModelFactory/load(hub:configuration:progressHandler:)``
+/// to determine the type of model to load.
+public struct BaseConfiguration: Codable, Sendable {
```
Comment (davidkoski) [inline Libraries/MLXLMCommon/BaseConfiguration.swift:10]: Extracted this from LanguageModel.swift as it is big enough to be its own thing.

File: Libraries/MLXLMCommon/BaseConfiguration.swift [hunk 3]
```diff
@@ -0,0 +1,155 @@
...
+    ///     "group_size": 64,
+    ///     "bits": 4,
+    ///     "model.embed_tokens": {
+    ///         "group_size": 32,
+    ///         "bits": 4
+    ///     },
+    ///     "model.layers.0.self_attn.q_norm": false,
+    /// ```
+    ///
+    /// This mixed type structure requires manual decoding.
```
Comment (davidkoski) [inline Libraries/MLXLMCommon/BaseConfiguration.swift:78]: This turned out to be a bit tricky.  We have:

- quantization ints
- dictionary keys -> quantization structs
- dictionary keys -> bools

all mixed in the one dictionary.  We could treat it as an unstructured bag (like Python) but that isn't how we usually play it in swift.  We can handle it with a custom Codable implementation

File: Libraries/Embedders/BaseConfiguration.swift [hunk 4]
```diff
@@ -0,0 +1,156 @@
...
+                case .skip:
+                    try container.encode(false, forKey: .init(stringValue: key))
+                case .quantize(let q):
+                    try container.encode(q, forKey: .init(stringValue: key))
+                }
+            }
+        }
+    }
+
+    var quanitzationContainer: QuantizationContainer?
```
Comment (davidkoski) [inline Libraries/Embedders/BaseConfiguration.swift:141]: internal bits -- this is the combined dictionary

File: Libraries/MLXLMCommon/BaseConfiguration.swift [hunk 5]
```diff
@@ -0,0 +1,156 @@
...
+                case .skip:
+                    try container.encode(false, forKey: .init(stringValue: key))
+                case .quantize(let q):
+                    try container.encode(q, forKey: .init(stringValue: key))
+                }
+            }
+        }
+    }
+
+    var quanitzationContainer: QuantizationContainer?
```
Comment (davidkoski) [inline Libraries/MLXLMCommon/BaseConfiguration.swift:141]: internal bits -- this is the combined dictionary

File: Libraries/MLXLMCommon/BaseConfiguration.swift [hunk 6]
```diff
@@ -0,0 +1,156 @@
...
+
+    @available(*, deprecated, message: "Please use perLayerQuantization instead")
+    public var quantization: Quantization? {
```
Comment (davidkoski) [inline Libraries/MLXLMCommon/BaseConfiguration.swift:144]: the single quantization value -- shouldn't use this

File: Libraries/MLXLMCommon/Load.swift [hunk 7]
```diff
@@ -78,10 +80,17 @@ public func loadWeights(
...
     // quantize if needed
-    if let quantization {
-        quantize(model: model, groupSize: quantization.groupSize, bits: quantization.bits) {
-            path, module in
-            weights["\(path).scales"] != nil
+    if quantization != nil || perLayerQuantization != nil {
+        quantize(model: model) { path, module in
+            if weights["\(path).scales"] != nil {
+                if let perLayerQuantization {
+                    return perLayerQuantization.quantization(layer: path)?.asTuple
```
Comment (davidkoski) [inline Libraries/MLXLMCommon/Load.swift:87]: Use the per layer values (this allows `false` to mean no quant and falls back to the default if an unknown key)

File: Libraries/MLXLMCommon/Load.swift [hunk 8]
```diff
@@ -91,3 +100,26 @@ public func loadWeights(
 
     eval(model)
 }
+
+// TODO remove once mlx-swift update is adopted
+func quantize(
```
Comment (davidkoski) [inline Libraries/MLXLMCommon/Load.swift:105]: See https://github.com/ml-explore/mlx-swift/pull/229

File: Applications/LLMEval/ContentView.swift [hunk 9]
```diff
@@ -40,7 +40,8 @@ struct ContentView: View {
                     .frame(maxWidth: 350, alignment: .leading)
                     Toggle(isOn: $llm.enableThinking) {
                         Text("Thinking")
-                            .help("Switches between thinking and non-thinking modes. Support: Qwen3")
+                            .help(
+                                "Switches between thinking and non-thinking modes. Support: Qwen3")
```
Comment (davidkoski) [inline Applications/LLMEval/ContentView.swift:44]: I am a little confused here -- #290 fixed this (though it seems not to have run CI either).  swift-format complained about this code and I applied it again, _but_ `main` actually has this code:

https://github.com/ml-explore/mlx-swift-examples/blob/main/Applications/LLMEval/ContentView.swift#L43

The `-` line doesn't match main.

Comment (davidkoski) [reply Applications/LLMEval/ContentView.swift]: Haha, I should have realized.  Branched off the wrong point in main.

File: Libraries/Embedders/BaseConfiguration.swift (hunk 1 above)
Comment (awni) [reply Libraries/Embedders/BaseConfiguration.swift:10]: Possibly. Though I don't know of any packages which produces mixed quant embedding models. So it's also fine to leave this out. Or we can support it.. since you have it already in case it does come up.

**Review by awni — APPROVED** [review]
Looks great!! Thanks for adding that!
