### PR TITLE
Fix #250 -- qwen2vl size configuration moved

### LINKED ISSUE #250: keyNotFound exception when loading model using VLMModelFactory.shared.loadContainer in VLMEval
I'm running the VLMEval application from the main branch and gets the below error when loading ModelRegistry.qwen2VL2BInstruct4Bit.

Failed: keyNotFound(CodingKeys(stringValue: "size", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"size\", intValue: nil) (\"size\").", underlyingError: nil))

Any clue?

### PR DESCRIPTION
**Pull request by davidkoski**
- size configuration moved from size.min_pixels to just min_pixels
- accept either

### CODE REVIEW

File: Libraries/MLXVLM/Models/Qwen2VL.swift [hunk 1]
```diff
@@ -1040,11 +1040,21 @@ public struct Qwen2VLProcessorConfiguration: Codable, Sendable {
...
+    private let _size: Size?
+    private let _maxPixels: Int?
+    private let _minPixels: Int?
+
+    public var minPixels: Int {
+        _minPixels ?? _size?.minPixels ?? 3136
+    }
+    public var maxPixels: Int {
+        _maxPixels ?? _size?.maxPixels ?? 12_845_056
+    }
```
Comment (davidkoski) [inline Libraries/MLXVLM/Models/Qwen2VL.swift:1056]: This will accept either top level keys or nested in size (in case somebody has an older config).
